### ISSUE TITLE
PermissionManager missing undefined function definition from MagmaMc.Utils [2.0.0]

### ISSUE THREAD

**Issue by braddevans** [MagmaMcNet/PermissionManager#1]
### package versions:
 - (vcc) MagmaMc.Utils [2.0.0] (latest)
 - (vcc) MagmaMc.PermissionManager [1.1.0] (latest)

### Provided error:
```
Packages\dev.magmamc.permissionmanager\Editor\PermissiveEventEditor.cs(69,25): error CS0117: 'EditorUtilities' does not contain a definition for 'DrawDoubleList'
```

### line contents:
```
EditorUtilities.DrawDoubleList(AuthorizedReceivers, AuthorizedEvents, "Authorized", ref a);
```

### screenshots:
![image](https://github.com/MagmaMcNet/PermissionManager/assets/7889253/4bfb9d92-da57-41f6-9b57-58146a6c9c67)

**Comment by MagmaVRC** [comment]
issue was due to Incorrect Function Name on Utils has been fixed here 
[2.0.1](https://github.com/MagmaMcNet/Utils/releases/tag/2.0.1)
